apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
  clusterIP: None
  selector:
    role: mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim-secrets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
          - name: secrets-volume
            readOnly: true
            mountPath: /etc/secrets-volume
          - name: mongodb-persistent-storage-claim
            mountPath: /data/db
      volumes:
      - name: secrets-volume
        persistentVolumeClaim:
          claimName: mongo-pv-claim-secrets
      - name: mongodb-persistent-storage-claim
        persistentVolumeClaim:
          claimName: mongo-pv-claim